language: php

php:
    - 7.1
    - 7.2
    - 7.3

jobs:
  include:
    -   name: Lowest Dependencies
        install:
          - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


    -   stage: Nette Tester
        php:
          - 7.1
          - 7.2
          - 7.3
        install:
          - travis_retry pear config-set preferred_state beta
          - travis_retry pecl channel-update pecl.php.net
          - travis_retry yes | pecl install imagick
          - travis_retry composer install --no-progress --prefer-dist

        script:
          - php temp/phpstan/phpstan.phar analyse --autoload-file vendor/autoload.php --level 7 src


    -   stage: Static Analysis (informative)
        php:
          - 7.1
          - 7.2
          - 7.3
        install:
          # Install PHPStan
          - travis_retry composer create-project phpstan/phpstan-shim temp/phpstan --no-progress
          - travis_retry composer install --no-progress --prefer-dist
        script:
          - vendor/bin/tester tests -C -s


    -   stage: Nette Coding Standard
        php:
          - 7.1
          - 7.2
          - 7.3
        install:
            - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
        script:
            - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml