language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
    - pear config-set preferred_state beta
    - pecl channel-update pecl.php.net
    - yes | pecl install imagick
    - composer install

script: vendor/bin/tester tests -C -s
